# Generated by Django 2.2 on 2019-09-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quest_Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Имя автора')),
                ('author_mail', models.EmailField(max_length=254, verbose_name='Почта автора')),
                ('text', models.TextField(max_length=2000, verbose_name='Текст записи')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('blocked', 'Заблокировано')], default='active', max_length=50, verbose_name='Статус')),
            ],
        ),
    ]
