# Generated by Django 2.2 on 2019-09-21 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quest_Book',
            new_name='QuestBook',
        ),
    ]
